spring:
  application:
    name: gym-api

  datasource:
    url: jdbc:postgresql://localhost:5434/gymapp
    username: postgres
    password: marco123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081